# Data Structures & Control Structures:

### 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse

In [33]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [34]:
# Append Opr.
list.append(10)
list

[1, 2, 3, 4, 5, 10]

In [35]:
# Extend Opr.
list.extend([20,30,40])

In [36]:
list

[1, 2, 3, 4, 5, 10, 20, 30, 40]

In [37]:
# Insert Opr.
list.insert(5,6)

In [38]:
list

[1, 2, 3, 4, 5, 6, 10, 20, 30, 40]

In [39]:
# Remove Opr.
list.remove(10)
list

[1, 2, 3, 4, 5, 6, 20, 30, 40]

In [40]:
# POP Opr.
list.pop(7)
list 

[1, 2, 3, 4, 5, 6, 20, 40]

In [41]:
list1=list.copy()

In [42]:
list1

[1, 2, 3, 4, 5, 6, 20, 40]

In [43]:
# Clear Opr.
list.clear()

In [44]:
list

[]

In [45]:
# Index Opr.
list1.index(6)

5

In [50]:
# Count Opr.
print(list1.count(30))
print(list1.count(40))

0
1


In [53]:
# Sort Opr.
list1.sort()
list1

[1, 2, 3, 4, 5, 6, 20, 40]

In [54]:
list1.reverse()
list1

[40, 20, 6, 5, 4, 3, 2, 1]

### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [55]:
students=('akash','sanju','sam')
print(students)

('akash', 'sanju', 'sam')


In [56]:
students[1]='sanjay'

TypeError: 'tuple' object does not support item assignment

###### since,tuple is immutable so we cant change,insert or remove its elements.

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [60]:
sets={1,2,3,4,5,2,4,6}
print('Sets:',sets)

Sets: {1, 2, 3, 4, 5, 6}


###### sets do not allow duplicates since we added 2 and 4 multiple times they appear only once 

### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [64]:
emp={'name':'akash','age':21,'city':'blr'}
print(emp)

{'name': 'akash', 'age': 21, 'city': 'blr'}


In [65]:
#Update ahe
emp['age']=22

In [66]:
emp

{'name': 'akash', 'age': 22, 'city': 'blr'}

In [67]:
# add key mail
emp['email']='akash123@gmial.com'

In [68]:
print('final dict:',emp)

final dict: {'name': 'akash', 'age': 22, 'city': 'blr', 'email': 'akash123@gmial.com'}


### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [69]:
age=int(input('enetr your age:'))
if age>=18:
    print('eligble to vote')
else:
    print('not eligible to vote')

enetr your age: 18


eligble to vote


In [70]:
age=int(input('enetr your age:'))
if age>=18:
    print('eligble to vote')
else:
    print('not eligible to vote')

enetr your age: 17


not eligible to vote


### 6.	Given a 'marks' variable, print the grade:
### - 90 and above: 'A'
### - 75–89: 'B'
### - 50–74: 'C'
### - Below 50: 'Fail'


In [76]:
marks=int(input('enter marks:'))
if marks>=90:
    print('grade: A')
elif marks>=75:
    print('grade: B')
elif marks>=50:
    print('grade: C')
else:
    print ('fail')

enter marks: 40


fail


In [75]:
marks=int(input('enter marks:'))
if marks>=90:
    print('grade: A')
elif marks>=75:
    print('grade: B')
elif marks>=50:
    print('grade: C')
else:
    print ('fail')

enter marks: 76


grade: B


In [77]:
marks=int(input('enter marks:'))
if marks>=90:
    print('grade: A')
elif marks>=75:
    print('grade: B')
elif marks>=50:
    print('grade: C')
else:
    print ('fail')

enter marks: 92


grade: A


In [78]:
marks=int(input('enter marks:'))
if marks>=90:
    print('grade: A')
elif marks>=75:
    print('grade: B')
elif marks>=50:
    print('grade: C')
else:
    print ('fail')

enter marks: 60


grade: C


### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [83]:
num=int(input('enter a nuber'))
if num>0:
    if num %2==0:
        print('numbr is +ve and even')
    else:
        print('numbr is +ve and odd')
elif num==0:
    print('number is zero')
else:
    print('number is negative')

enter a nuber 0


number is zero


In [84]:
num=int(input('enter a nuber'))
if num>0:
    if num %2==0:
        print('numbr is +ve and even')
    else:
        print('numbr is +ve and odd')
elif num==0:
    print('number is zero')
else:
    print('number is negative')

enter a nuber -2


number is negative


In [85]:
num=int(input('enter a nuber'))
if num>0:
    if num %2==0:
        print('numbr is +ve and even')
    else:
        print('numbr is +ve and odd')
elif num==0:
    print('number is zero')
else:
    print('number is negative')

enter a nuber 2


numbr is +ve and even


In [86]:
num=int(input('enter a nuber'))
if num>0:
    if num %2==0:
        print('numbr is +ve and even')
    else:
        print('numbr is +ve and odd')
elif num==0:
    print('number is zero')
else:
    print('number is negative')

enter a nuber 1


numbr is +ve and odd


# Numpy

### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [101]:
import numpy as np

In [93]:
zero_dim=np.array(5)
print('0-D:',zero_dim)
print('0-D:',zero_dim.ndim)

0-D: 5
0-D: 0


In [94]:
one_dim=np.array([1,2,3,4,5])
print('1-D:',one_dim)
print('1-D:',one_dim.ndim)

1-D: [1 2 3 4 5]
1-D: 1


In [95]:
two_dim=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print('2-D:',two_dim)
print('2-D:',two_dim.ndim)

2-D: [[1 2 3 4 5]
 [6 7 8 9 0]]
2-D: 2


### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [108]:
arr=np.random.randint(0,101,size=(4,4))
print(arr)

[[24 96 31 33]
 [11 92 29 20]
 [78 29 21 61]
 [92 90 91 38]]


### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [109]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [119]:
import pandas as pd
df=pd.DataFrame(arr,columns=['A','B','C'])

In [125]:
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# Exploring Pandas

### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [155]:
import pandas as pd
import numpy as np

In [184]:
data={'name':['akash','sanju','sam','sanju','manu','kedar','aman','kiran','abhi','varun'],
     'age':[18,19,20,19,22,23,24,25,20,21],'city':['blr','goa','pune','goa','kerala','blr','goa','pune','delhi','kerala'],
      'salary':[10000,20000,60000,20000,np.nan,50000,40000,70000,np.nan,80000]}

In [185]:
df=pd.DataFrame(data)

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    10 non-null     object 
 1   age     10 non-null     int64  
 2   city    10 non-null     object 
 3   salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes


In [187]:
df.describe()

,age,salary
count,10.000000,8.000000
mean,21.100000,43750.000000
std,2.330951,25599.944196
min,18.000000,10000.000000
25%,19.250000,20000.000000
50%,20.500000,45000.000000
75%,22.750000,62500.000000
max,25.000000,80000.000000


In [188]:
print(df[['name','city']])

    name    city
0  akash     blr
1  sanju     goa
2    sam    pune
3  sanju     goa
4   manu  kerala
5  kedar     blr
6   aman     goa
7  kiran    pune
8   abhi   delhi
9  varun  kerala


In [189]:
df.drop(columns=['city'])

,name,age,salary
0,akash,18,10000.0
1,sanju,19,20000.0
2,sam,20,60000.0
3,sanju,19,20000.0
4,manu,22,NaN
5,kedar,23,50000.0
6,aman,24,40000.0
7,kiran,25,70000.0
8,abhi,20,NaN
9,varun,21,80000.0


In [190]:
df['salary'].fillna(df['salary'].mean(),inplace=True)

In [191]:
df

,name,age,city,salary
0,akash,18,blr,10000.0
1,sanju,19,goa,20000.0
2,sam,20,pune,60000.0
3,sanju,19,goa,20000.0
4,manu,22,kerala,43750.0
5,kedar,23,blr,50000.0
6,aman,24,goa,40000.0
7,kiran,25,pune,70000.0
8,abhi,20,delhi,43750.0
9,varun,21,kerala,80000.0


In [192]:
duplicates=df.drop_duplicates()
duplicates

,name,age,city,salary
0,akash,18,blr,10000.0
1,sanju,19,goa,20000.0
2,sam,20,pune,60000.0
4,manu,22,kerala,43750.0
5,kedar,23,blr,50000.0
6,aman,24,goa,40000.0
7,kiran,25,pune,70000.0
8,abhi,20,delhi,43750.0
9,varun,21,kerala,80000.0
